# These are supported funding model platforms

github: [AstralisSomnium]
patreon: SprdStakePool
custom: ['https://www.paypal.com/donate?token=b3-TcfSTSH0JfYJK1wYZ03Hr2htK5mqFsKY-IUOb8vazoWOp84099HS-vf5NIURjfjrD4DeURx9TaAH1']
