/* 
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.2.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ApiEra
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiEra
    {
        /// <summary>
        /// Enum Byron for value: byron
        /// </summary>
        [EnumMember(Value = "byron")]
        Byron = 1,
        /// <summary>
        /// Enum Shelley for value: shelley
        /// </summary>
        [EnumMember(Value = "shelley")]
        Shelley = 2,
        /// <summary>
        /// Enum Allegra for value: allegra
        /// </summary>
        [EnumMember(Value = "allegra")]
        Allegra = 3,
        /// <summary>
        /// Enum Mary for value: mary
        /// </summary>
        [EnumMember(Value = "mary")]
        Mary = 4    }
}
