/* 
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.2.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ApiGetSettings
    /// </summary>
    [DataContract]
        public partial class ApiGetSettings :  IEquatable<ApiGetSettings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiGetSettings" /> class.
        /// </summary>
        /// <param name="poolMetadataSource">Pool metadata source. This sets the metadata fetching strategy.  Possible values are   * none -&gt; no fetching   * direct -&gt; direct fetching   * uri -&gt; use SMASH server  (required).</param>
        public ApiGetSettings(string poolMetadataSource = default(string))
        {
            // to ensure "poolMetadataSource" is required (not null)
            if (poolMetadataSource == null)
            {
                throw new InvalidDataException("poolMetadataSource is a required property for ApiGetSettings and cannot be null");
            }
            else
            {
                this.PoolMetadataSource = poolMetadataSource;
            }
        }
        
        /// <summary>
        /// Pool metadata source. This sets the metadata fetching strategy.  Possible values are   * none -&gt; no fetching   * direct -&gt; direct fetching   * uri -&gt; use SMASH server 
        /// </summary>
        /// <value>Pool metadata source. This sets the metadata fetching strategy.  Possible values are   * none -&gt; no fetching   * direct -&gt; direct fetching   * uri -&gt; use SMASH server </value>
        [DataMember(Name="pool_metadata_source", EmitDefaultValue=false)]
        public string PoolMetadataSource { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiGetSettings {\n");
            sb.Append("  PoolMetadataSource: ").Append(PoolMetadataSource).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiGetSettings);
        }

        /// <summary>
        /// Returns true if ApiGetSettings instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiGetSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiGetSettings input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PoolMetadataSource == input.PoolMetadataSource ||
                    (this.PoolMetadataSource != null &&
                    this.PoolMetadataSource.Equals(input.PoolMetadataSource))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PoolMetadataSource != null)
                    hashCode = hashCode * 59 + this.PoolMetadataSource.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
