/* 
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.2.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Gives an indication if metadata GC checking for delisted pools has run and if so, when.  Possible values are:   - not_applicable -&gt; we&#x27;re currently not querying a SMASH server for metadata   - not_started -&gt; the GC hasn&#x27;t started yet, try again in a short while   - restarting -&gt; the GC thread is currently restarting, try again in short while   - has_run -&gt; the GC has run successfully  When &#x27;status&#x27; is &#x27;restarting&#x27; or &#x27;has_run&#x27; then the field &#x27;last_run&#x27; is set to the last GC time in UTC. 
    /// </summary>
    [DataContract]
        public partial class ApiMaintenanceActionGcStakePools :  IEquatable<ApiMaintenanceActionGcStakePools>, IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum StatusEnum
        {
            /// <summary>
            /// Enum Notapplicable for value: not_applicable
            /// </summary>
            [EnumMember(Value = "not_applicable")]
            Notapplicable = 1,
            /// <summary>
            /// Enum Notstarted for value: not_started
            /// </summary>
            [EnumMember(Value = "not_started")]
            Notstarted = 2,
            /// <summary>
            /// Enum Restarting for value: restarting
            /// </summary>
            [EnumMember(Value = "restarting")]
            Restarting = 3,
            /// <summary>
            /// Enum Hasrun for value: has_run
            /// </summary>
            [EnumMember(Value = "has_run")]
            Hasrun = 4        }
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiMaintenanceActionGcStakePools" /> class.
        /// </summary>
        /// <param name="status">status (required).</param>
        /// <param name="lastRun">lastRun.</param>
        public ApiMaintenanceActionGcStakePools(StatusEnum status = default(StatusEnum), string lastRun = default(string))
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for ApiMaintenanceActionGcStakePools and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            this.LastRun = lastRun;
        }
        

        /// <summary>
        /// Gets or Sets LastRun
        /// </summary>
        [DataMember(Name="last_run", EmitDefaultValue=false)]
        public string LastRun { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiMaintenanceActionGcStakePools {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  LastRun: ").Append(LastRun).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiMaintenanceActionGcStakePools);
        }

        /// <summary>
        /// Returns true if ApiMaintenanceActionGcStakePools instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiMaintenanceActionGcStakePools to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiMaintenanceActionGcStakePools input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.LastRun == input.LastRun ||
                    (this.LastRun != null &&
                    this.LastRun.Equals(input.LastRun))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.LastRun != null)
                    hashCode = hashCode * 59 + this.LastRun.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
