/* 
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.2.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The maintenance action to carry out, current values are   - gc_stake_pools -&gt; trigger looking up delisted pools from the remote SMASH server 
    /// </summary>
    [DataContract]
        public partial class ApiMaintenanceActionPostData :  IEquatable<ApiMaintenanceActionPostData>, IValidatableObject
    {
        /// <summary>
        /// Defines MaintenanceAction
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum MaintenanceActionEnum
        {
            /// <summary>
            /// Enum Pools for value: gc_stake_pools
            /// </summary>
            [EnumMember(Value = "gc_stake_pools")]
            Pools = 1        }
        /// <summary>
        /// Gets or Sets MaintenanceAction
        /// </summary>
        [DataMember(Name="maintenance_action", EmitDefaultValue=false)]
        public MaintenanceActionEnum MaintenanceAction { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiMaintenanceActionPostData" /> class.
        /// </summary>
        /// <param name="maintenanceAction">maintenanceAction (required).</param>
        public ApiMaintenanceActionPostData(MaintenanceActionEnum maintenanceAction = default(MaintenanceActionEnum))
        {
            // to ensure "maintenanceAction" is required (not null)
            if (maintenanceAction == null)
            {
                throw new InvalidDataException("maintenanceAction is a required property for ApiMaintenanceActionPostData and cannot be null");
            }
            else
            {
                this.MaintenanceAction = maintenanceAction;
            }
        }
        

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiMaintenanceActionPostData {\n");
            sb.Append("  MaintenanceAction: ").Append(MaintenanceAction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiMaintenanceActionPostData);
        }

        /// <summary>
        /// Returns true if ApiMaintenanceActionPostData instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiMaintenanceActionPostData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiMaintenanceActionPostData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MaintenanceAction == input.MaintenanceAction ||
                    (this.MaintenanceAction != null &&
                    this.MaintenanceAction.Equals(input.MaintenanceAction))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MaintenanceAction != null)
                    hashCode = hashCode * 59 + this.MaintenanceAction.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
