/* 
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.2.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Restore from root private key
    /// </summary>
    [DataContract]
        public partial class ApiWalletPostData :  IEquatable<ApiWalletPostData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiWalletPostData" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="mnemonicSentence">A list of mnemonic words (required).</param>
        /// <param name="mnemonicSecondFactor">An optional passphrase used to encrypt the mnemonic sentence..</param>
        /// <param name="passphrase">A master passphrase to lock and protect the wallet for sensitive operation (e.g. sending funds) (required).</param>
        /// <param name="addressPoolGap">Number of consecutive unused addresses allowed.  **IMPORTANT DISCLAIMER:** Using values other than &#x60;20&#x60; automatically makes your wallet invalid with regards to BIP-44 address discovery. It means that you **will not** be able to fully restore your wallet in a different software which is strictly following BIP-44.  Beside, using large gaps is **not recommended** as it may induce important performance degradations. Use at your own risks.  (default to 20).</param>
        public ApiWalletPostData(string name = default(string), List<string> mnemonicSentence = default(List<string>), List<string> mnemonicSecondFactor = default(List<string>), string passphrase = default(string), int? addressPoolGap = 20)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for ApiWalletPostData and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "mnemonicSentence" is required (not null)
            if (mnemonicSentence == null)
            {
                throw new InvalidDataException("mnemonicSentence is a required property for ApiWalletPostData and cannot be null");
            }
            else
            {
                this.MnemonicSentence = mnemonicSentence;
            }
            // to ensure "passphrase" is required (not null)
            if (passphrase == null)
            {
                throw new InvalidDataException("passphrase is a required property for ApiWalletPostData and cannot be null");
            }
            else
            {
                this.Passphrase = passphrase;
            }
            this.MnemonicSecondFactor = mnemonicSecondFactor;
            // use default value if no "addressPoolGap" provided
            if (addressPoolGap == null)
            {
                this.AddressPoolGap = 20;
            }
            else
            {
                this.AddressPoolGap = addressPoolGap;
            }
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// A list of mnemonic words
        /// </summary>
        /// <value>A list of mnemonic words</value>
        [DataMember(Name="mnemonic_sentence", EmitDefaultValue=false)]
        public List<string> MnemonicSentence { get; set; }

        /// <summary>
        /// An optional passphrase used to encrypt the mnemonic sentence.
        /// </summary>
        /// <value>An optional passphrase used to encrypt the mnemonic sentence.</value>
        [DataMember(Name="mnemonic_second_factor", EmitDefaultValue=false)]
        public List<string> MnemonicSecondFactor { get; set; }

        /// <summary>
        /// A master passphrase to lock and protect the wallet for sensitive operation (e.g. sending funds)
        /// </summary>
        /// <value>A master passphrase to lock and protect the wallet for sensitive operation (e.g. sending funds)</value>
        [DataMember(Name="passphrase", EmitDefaultValue=false)]
        public string Passphrase { get; set; }

        /// <summary>
        /// Number of consecutive unused addresses allowed.  **IMPORTANT DISCLAIMER:** Using values other than &#x60;20&#x60; automatically makes your wallet invalid with regards to BIP-44 address discovery. It means that you **will not** be able to fully restore your wallet in a different software which is strictly following BIP-44.  Beside, using large gaps is **not recommended** as it may induce important performance degradations. Use at your own risks. 
        /// </summary>
        /// <value>Number of consecutive unused addresses allowed.  **IMPORTANT DISCLAIMER:** Using values other than &#x60;20&#x60; automatically makes your wallet invalid with regards to BIP-44 address discovery. It means that you **will not** be able to fully restore your wallet in a different software which is strictly following BIP-44.  Beside, using large gaps is **not recommended** as it may induce important performance degradations. Use at your own risks. </value>
        [DataMember(Name="address_pool_gap", EmitDefaultValue=false)]
        public int? AddressPoolGap { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiWalletPostData {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  MnemonicSentence: ").Append(MnemonicSentence).Append("\n");
            sb.Append("  MnemonicSecondFactor: ").Append(MnemonicSecondFactor).Append("\n");
            sb.Append("  Passphrase: ").Append(Passphrase).Append("\n");
            sb.Append("  AddressPoolGap: ").Append(AddressPoolGap).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiWalletPostData);
        }

        /// <summary>
        /// Returns true if ApiWalletPostData instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiWalletPostData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiWalletPostData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.MnemonicSentence == input.MnemonicSentence ||
                    this.MnemonicSentence != null &&
                    input.MnemonicSentence != null &&
                    this.MnemonicSentence.SequenceEqual(input.MnemonicSentence)
                ) && 
                (
                    this.MnemonicSecondFactor == input.MnemonicSecondFactor ||
                    this.MnemonicSecondFactor != null &&
                    input.MnemonicSecondFactor != null &&
                    this.MnemonicSecondFactor.SequenceEqual(input.MnemonicSecondFactor)
                ) && 
                (
                    this.Passphrase == input.Passphrase ||
                    (this.Passphrase != null &&
                    this.Passphrase.Equals(input.Passphrase))
                ) && 
                (
                    this.AddressPoolGap == input.AddressPoolGap ||
                    (this.AddressPoolGap != null &&
                    this.AddressPoolGap.Equals(input.AddressPoolGap))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.MnemonicSentence != null)
                    hashCode = hashCode * 59 + this.MnemonicSentence.GetHashCode();
                if (this.MnemonicSecondFactor != null)
                    hashCode = hashCode * 59 + this.MnemonicSecondFactor.GetHashCode();
                if (this.Passphrase != null)
                    hashCode = hashCode * 59 + this.Passphrase.GetHashCode();
                if (this.AddressPoolGap != null)
                    hashCode = hashCode * 59 + this.AddressPoolGap.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
