/* 
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.2.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WalletswalletIdtransactionsWithdrawals
    /// </summary>
    [DataContract]
        public partial class WalletswalletIdtransactionsWithdrawals :  IEquatable<WalletswalletIdtransactionsWithdrawals>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletswalletIdtransactionsWithdrawals" /> class.
        /// </summary>
        /// <param name="stakeAddress">stakeAddress (required).</param>
        /// <param name="amount">amount (required).</param>
        public WalletswalletIdtransactionsWithdrawals(string stakeAddress = default(string), WalletswalletIdpaymentfeesAmount amount = default(WalletswalletIdpaymentfeesAmount))
        {
            // to ensure "stakeAddress" is required (not null)
            if (stakeAddress == null)
            {
                throw new InvalidDataException("stakeAddress is a required property for WalletswalletIdtransactionsWithdrawals and cannot be null");
            }
            else
            {
                this.StakeAddress = stakeAddress;
            }
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new InvalidDataException("amount is a required property for WalletswalletIdtransactionsWithdrawals and cannot be null");
            }
            else
            {
                this.Amount = amount;
            }
        }
        
        /// <summary>
        /// Gets or Sets StakeAddress
        /// </summary>
        [DataMember(Name="stake_address", EmitDefaultValue=false)]
        public string StakeAddress { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public WalletswalletIdpaymentfeesAmount Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WalletswalletIdtransactionsWithdrawals {\n");
            sb.Append("  StakeAddress: ").Append(StakeAddress).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WalletswalletIdtransactionsWithdrawals);
        }

        /// <summary>
        /// Returns true if WalletswalletIdtransactionsWithdrawals instances are equal
        /// </summary>
        /// <param name="input">Instance of WalletswalletIdtransactionsWithdrawals to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WalletswalletIdtransactionsWithdrawals input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StakeAddress == input.StakeAddress ||
                    (this.StakeAddress != null &&
                    this.StakeAddress.Equals(input.StakeAddress))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StakeAddress != null)
                    hashCode = hashCode * 59 + this.StakeAddress.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
