/* 
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.2.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// A delegation action.  Pool id is only required for \&quot;join\&quot;. 
    /// </summary>
    [DataContract]
        public partial class WalletswalletIdcoinselectionsrandomDelegationAction :  IEquatable<WalletswalletIdcoinselectionsrandomDelegationAction>, IValidatableObject
    {
        /// <summary>
        /// Defines Action
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ActionEnum
        {
            /// <summary>
            /// Enum Quit for value: quit
            /// </summary>
            [EnumMember(Value = "quit")]
            Quit = 1,
            /// <summary>
            /// Enum Join for value: join
            /// </summary>
            [EnumMember(Value = "join")]
            Join = 2        }
        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="action", EmitDefaultValue=false)]
        public ActionEnum Action { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletswalletIdcoinselectionsrandomDelegationAction" /> class.
        /// </summary>
        /// <param name="action">action (required).</param>
        /// <param name="pool">A unique identifier for the pool..</param>
        public WalletswalletIdcoinselectionsrandomDelegationAction(ActionEnum action = default(ActionEnum), string pool = default(string))
        {
            // to ensure "action" is required (not null)
            if (action == null)
            {
                throw new InvalidDataException("action is a required property for WalletswalletIdcoinselectionsrandomDelegationAction and cannot be null");
            }
            else
            {
                this.Action = action;
            }
            this.Pool = pool;
        }
        

        /// <summary>
        /// A unique identifier for the pool.
        /// </summary>
        /// <value>A unique identifier for the pool.</value>
        [DataMember(Name="pool", EmitDefaultValue=false)]
        public string Pool { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WalletswalletIdcoinselectionsrandomDelegationAction {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Pool: ").Append(Pool).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WalletswalletIdcoinselectionsrandomDelegationAction);
        }

        /// <summary>
        /// Returns true if WalletswalletIdcoinselectionsrandomDelegationAction instances are equal
        /// </summary>
        /// <param name="input">Instance of WalletswalletIdcoinselectionsrandomDelegationAction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WalletswalletIdcoinselectionsrandomDelegationAction input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) && 
                (
                    this.Pool == input.Pool ||
                    (this.Pool != null &&
                    this.Pool.Equals(input.Pool))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.Pool != null)
                    hashCode = hashCode * 59 + this.Pool.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
